apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  labels:
    app: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: gcr.io/soa-calc/calculator/calculator:latest
          args:
            - multiplier=multiplier-svc.default.svc.cluster.local:3000
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-svc
spec:
  selector:
    app: calculator
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80