apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorialiser
  namespace: calculator
  labels:
    app: factorialiser
spec:
  selector:
    matchLabels:
      app: factorialiser
  template:
    metadata:
      labels:
        app: factorialiser
    spec:
      containers:
        - name: factorialiser
          image: gcr.io/soa-calc/calculator/factorialiser:latest
          args:
            - "-multiplier=$(MULTIPLIER_RPC_DNS)"
          ports:
            - containerPort: 3000
          env:
            - name: MULTIPLIER_RPC_DNS
              valueFrom:
                configMapKeyRef:
                  key: multiplier.rpc.dns
                  name: service-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: calculator
  name: factorialiser-svc
spec:
  selector:
    app: factorialiser
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000